apiVersion: v1
name: magento1
version: 6.4.4
description: Hevelop helm chart for mangento1.
keywords:
- magento
- e-commerce
- http
- web
- php
home: https://magento.com/
sources:
- https://github.com/Hevelop/helm-chart-magento1
maintainers:
- name: Hevelop
  email: systems@hevelop.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-110x117.png
dependencies:
  - name: mariadb
    version: 5.x.x
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mariadb.enabled
  - name: efs-provisioner
    version: 0.x.x
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: efs.enabled
