{{- if .Values.cms.httpd.enabled }}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "magento.fullname" . }}-cms-httpd
  labels:
    app: {{ template "magento.fullname" . }}-cms-httpd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.httpd.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.cms.httpd.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.cms.httpd.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ template "magento.fullname" . }}-cms-httpd
  template:
    metadata:
      labels:
        app: {{ template "magento.fullname" . }}-cms-httpd
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}  
      {{- end }}
    spec:
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end }}
      initContainers:
      - name: wait-php-fpm
        image: jwilder/dockerize        
        args: 
        - '-wait'
        - "tcp://{{ template "magento.fullname" . }}-cms-phpfpm:9000"
        - '-timeout'
        - '180s'
      containers:
      - name: {{ template "magento.fullname" . }}-cms-httpd
        image: {{ template "httpdcms.image" . }}
        imagePullPolicy: {{ .Values.cms.httpd.pullPolicy | quote }}
        {{- if .Values.cms.httpd.lifecycle.preStopCommand }}
        lifecycle:
          preStop:
            exec:
              command: {{toJson .Values.cms.httpd.lifecycle.preStopCommand }}
        {{- end }}
        ports:
        - containerPort: 80
        {{- if .Values.cms.httpd.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if and .Values.cms.httpd.readinessProbe.enabled (not .Values.varnish.enabled) }}
        readinessProbe:
          httpGet:
            path: {{ .Values.cms.httpd.readinessProbe.path }}
            port: {{ .Values.cms.httpd.readinessProbe.port }}
            httpHeaders:
            - name: Host
              value: {{ .Values.global.host | quote }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        - name: httpd-conf
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
        - name: httpd-extra-conf
          mountPath: /usr/local/apache2/conf/extra/httpd-vhosts.conf
          subPath: httpd-vhosts.conf
        - name: httpd-extra-conf
          mountPath: /usr/local/apache2/conf/extra/httpd-remoteip.conf
          subPath: httpd-remoteip.conf
        - name: httpd-extra-conf
          mountPath: /usr/local/apache2/conf/extra/httpd-fcgi.conf
          subPath: httpd-fcgi.conf
        {{- if or .Values.efs.enabled .Values.efs.existingPvcName }}
        - mountPath: /efs
          name: efs
        {{- range $index, $val := .Values.efs.containerMountPaths }}
        - mountPath: "/var/www/deploy{{ $val }}"
          subPath: {{ (trimPrefix "/" $val) }}
          name: efs
        {{- end }}
        {{- end }}
        {{- if .Values.logs.enabled }}
        {{- range $index, $val := .Values.logs.containerMountPaths }}
        - mountPath: "{{ $.Values.logs.containerMountPath }}/{{ $val }}"
          subPath: {{ $val }}
          name: logs
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.cms.httpd.resources | indent 10 }}
      volumes:
      - name: httpd-conf
        configMap:
          name: {{ template "magento.fullname" . }}-cms-httpd-configmap
          items:
          - key: httpd.conf
            path: httpd.conf
      - name: httpd-extra-conf
        configMap:
          name: {{ template "magento.fullname" . }}-cms-httpd-configmap
          items:
          - key: httpd-vhosts.conf
            path: httpd-vhosts.conf
          - key: httpd-remoteip.conf
            path: httpd-remoteip.conf
          - key: httpd-fcgi.conf
            path: httpd-fcgi.conf
      {{- if .Values.efs.enabled }}
      - name: efs
        persistentVolumeClaim:
          claimName: {{ template "magento.fullname" . }}-efs-pvc
      {{- end }}
      {{- if .Values.logs.enabled }}
      - name: logs
        emptyDir: {}
      {{- end }}
      {{- if and .Values.efs.existingPvcName (not .Values.efs.enabled) }}
      - name: efs
        persistentVolumeClaim:
          claimName: {{ .Values.efs.existingPvcName }}
      {{- end }}
      # terminationGracePeriodSeconds: {{ .Values.cms.httpd.terminationGracePeriodSeconds | quote }}
{{- end }}
