apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "magento.fullname" . }}-httpd-configmap
  labels:
    app: {{ template "magento.fullname" . }}-httpd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- (tpl (.Files.Glob "config/httpd/*").AsConfig . ) | nindent 2 }}