apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "magento.fullname" . }}-httpd
  labels:
    app: {{ template "magento.fullname" . }}-httpd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "magento.fullname" . }}-httpd
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "magento.fullname" . }}-httpd
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}  
      {{- end }}
    spec:
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end }}
      containers:
      - name: {{ template "magento.fullname" . }}-httpd
        image: {{ template "httpd.image" . }}
        imagePullPolicy: {{ .Values.httpd.pullPolicy | quote }}
        env:
        - name: URL_ARCHIVE
          value: "{{ template "artifactFullUrl" . }}"
        - name: FCGI_HOST_AND_PORT
          value: "{{ template "magento.fullname" . }}-phpfpm:9000"
        ports:
        - containerPort: 80
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ .Values.host | quote }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ .Values.global.host | quote }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        - mountPath: /efs
          name: efs
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      {{- if .Values.efs.enabled }}
      - name: efs
        persistentVolumeClaim:
          claimName: {{ template "magento.fullname" . }}-efs-pvc
      {{- end }}