{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "magento.fullname" . }}-phpfpm
  labels:
    app: {{ template "magento.fullname" . }}-phpfpm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.phpfpm.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "magento.fullname" . }}-phpfpm
  template:
    metadata:
      labels:
        app: {{ template "magento.fullname" . }}-phpfpm
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}  
      {{- end }}
    spec:
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end }}
      containers:
      - name: {{ template "magento.fullname" . }}-phpfpm
        image: {{ template "phpfpm.image" . }}
        imagePullPolicy: {{ .Values.phpfpm.pullPolicy | quote }}
        env:
        - name: URL_ARCHIVE
          value: "{{ template "artifactFullUrl" . }}"
        {{- if .Values.phpfpm.processManager }}
        - name: PROCESS_MANAGER
          value: "{{ .Values.phpfpm.processManager }}"
        {{- end }}
        {{- if .Values.phpfpm.pmMaxChildren }}
        - name: PM_MAX_CHILDREN
          value: "{{ .Values.phpfpm.pmMaxChildren }}"
        {{- end }}
        {{- if .Values.phpfpm.PmProcessIdleTimeout }}
        - name: PM_PROCESS_IDLE_TIMEOUT
          value: "{{ .Values.phpfpm.PmProcessIdleTimeout }}"
        {{- end }}
        {{- if .Values.phpfpm.PmMaxRequests }}
        - name: PM_MAX_REQUESTS
          value: "{{ .Values.phpfpm.PmMaxRequests }}"
        {{- end }}
        {{- if .Values.phpfpm.RequestTerminateTimeout }}
        - name: REQUEST_TERMINATE_TIMEOUT
          value: "{{ .Values.phpfpm.RequestTerminateTimeout }}"
        {{- end }}
        ports:
        - containerPort: 9000
        {{- if .Values.phpfpm.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.phpfpm.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        {{- if or .Values.efs.enabled .Values.efs.existingPvcName }}
        - mountPath: /efs
          name: efs
        {{- range $index, $val := .Values.efs.containerMountPaths }}
        - mountPath: "/var/www/deploy{{ $val }}"
          subPath: {{ (trimPrefix "/" $val) }}
          name: efs
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.phpfpm.resources | indent 10 }}
      volumes:
      {{- if .Values.efs.enabled }}
      - name: efs
        persistentVolumeClaim:
          claimName: {{ template "magento.fullname" . }}-efs-pvc
      {{- end }}
      {{- if and .Values.efs.existingPvcName (not .Values.efs.enabled) }}
      - name: efs
        persistentVolumeClaim:
          claimName: {{ .Values.efs.existingPvcName }}
      {{- end }}